### PR TITLE
Update NativeIO name to Foundation Storage API

### PR DESCRIPTION
**Pull request by fivedots**
This PR updates the README and security questionnaire with our new name. The examples and IDL have not been updated, to avoid confusion until the change lands in Chrome.

I'll rename the repos and create redirects after this PR is merged.

### CODE REVIEW

**Review by rstz — APPROVED** [review]
You might want

**Comment by asutherland** [comment]
Is it possible to link to the discussion that led to the new name (if an online discussion) or provide a synopsis (if an offline discussion)?

**Comment by kaizhu256** [comment]
yea, the new name is confusing.  wasn't the whole point to provide/virtualize"native", system-level file-api's for emscripten/wasm-sqlite (something wicg's filesystem-api could not do)?

**Comment by fivedots** [comment]
Hello @asutherland, @kaizhu256, thanks for reaching out,

The reason the name was changed is two-fold:

- There is an overall effort in Chrome to make our codebase more inclusive (for an example in public documentation, Native is a discouraged term [here](https://developers.google.com/style/word-list#native))
- We received feedback that the name was unclear (both internally, and in our early [TAG review](https://github.com/w3ctag/design-reviews/issues/566), where Storage Foundation API was received positively)

After a long-running internal discussion, we settled on the new name because it nicely conveys the idea that this is a low-level API, and that one of its main use cases is to act as the basis for more complex storage semantics. Of course, we are open to feedback and change, especially if there are strong reasons on why we shouldn’t go for Storage Foundation API.

**Comment by kaizhu256** [comment]
are there use-cases outside of database/streaming-media? if not how about something along lines of `"dbfs" or "streamfs"`?

`"foundation-storage-api"` doesn't help in educating ppl why wicg-filesystem-access-api is inappropriate for above scenarios (and reason for this proposal).

**Comment by asutherland** [comment]
Thank you for the context and links!  The new name seems to nicely address both concerns!

**Pull request merged**
